# Pegnetd config file
[app]
  # MainNet/TestNet
  network = "TestNet"

  loglevel = "info"
  apilisten = "8070"
  # Hardcoding the mainnet path, but allowing for future net support
  dbpath   = "$HOME/.pegnetd/testnet/sql.db"

  pegnetd = "http://localhost:8070"
  server = "http://3.22.141.113:8088/v2"
  wallet = "http://localhost:8089/v2"
  walletUser = ""
  walletPass = ""
[dblocksync]
  retry = "5s"
