# Pegnetd config file
[app]
  loglevel = "info"
  apilisten = "8070"
  # Hardcoding the mainnet path, but allowing for future net support
  dbpath   = "$HOME/.pegnetd/mainnet/node.db"

  # EC3TsJHUs8bzbbVnratBafub6toRYdgzgbR7kWwCW4tqbmyySRmg
  ecPrivateKey = "Es2XT3jSxi1xqrDvS5JERM3W3jh1awRHuyoahn3hbQLyfEi1jvbq"

  pegnetd = "http://localhost:8070"
  server = "http://localhost:8088/v2"
  wallet = "http://localhost:8089/v2"
  walletUser = ""
  walletPass = ""

[dblocksync]
  retry = "5s"